 // Source code is unavailable, and was generated by the Fernflower decompiler.
package me.lythox.main.util;

import org.bukkit.Material;

public class MaterialData implements Cloneable {
    private final Material type;
    private byte data;


    public MaterialData(Material type, byte data) {
        this.type = type;
        this.data = data;
    }

    public MaterialData(Material type) {
        this(type, (byte)0);
    }


    public byte getData() {
        return this.data;
    }


    public void setData(byte data) {
        this.data = data;
    }


    public Material getItemType() {
        return this.type;
    }


    public String toString() {
        return this.getItemType() + "(" + this.getData() + ")";
    }


    public int hashCode() {
        return this.getItemType().hashCode() << 8 ^ this.getData();
    }


    public boolean equals(Object obj) {
        if (obj != null && obj instanceof MaterialData) {
            MaterialData md = (MaterialData)obj;

            return md.getItemType() == this.getItemType() && md.getData() == this.getData();
        } else {
            return false;
        }
    }


    public MaterialData clone() {
        try {
            return (MaterialData)super.clone();
        } catch (CloneNotSupportedException var2) {
            throw new Error(var2);
        }
    }
}